---
page_title: "Single instance with SSH access"
description: |-
  Launch a Linux instance with a public IP and SSH access, including the VPC, subnet, router, security group, and SSH key.
---

# Single instance with SSH access

This guide builds the minimum infrastructure to launch a Linux compute instance you can SSH into from the public internet. The example creates:

- A VPC + initial subnet
- A router with an external gateway (so traffic can leave the VPC)
- A router interface attaching the router to the subnet
- A security group allowing inbound SSH from anywhere
- An SSH key pair (generated by the platform if you don't supply a public key)
- The instance itself
- A floating IP and its association to the instance

After `terraform apply` you can connect with `ssh -i <private-key> ubuntu@<floating-ip>`.

## Complete example

```hcl
terraform {
  required_providers {
    acecloud = {
      source  = "AceCloudAI/acecloud"
      version = "~> 0.1"
    }
  }
}

provider "acecloud" {
  api_key_id           = var.acecloud_api_key_id
  api_key_secret       = var.acecloud_api_key_secret
  api_key_service_name = "terraform"
  region               = "ap-south-noi-1"
  project_id           = var.acecloud_project_id
}

# Look up the smallest CPU flavor and the latest Ubuntu image.
data "acecloud_flavors" "all" {}
data "acecloud_images" "all" {}

locals {
  flavor_id = [for f in data.acecloud_flavors.all.flavors : f.id if f.name == "C4i.medium"][0]
  image_id  = [for i in data.acecloud_images.all.images : i.id if i.name == "Ubuntu-24.04-LTS"][0]
}

# 1. Network
resource "acecloud_vpc" "main" {
  name              = "demo-vpc"
  description       = "VPC for the SSH-accessible instance demo"
  admin_state_up    = true
  subnet_name       = "demo-subnet"
  subnet_cidr       = "10.0.0.0/24"
  subnet_ip_version = 4
}

# Discover the public network UUID so the router can reach the internet.
data "acecloud_vpcs" "all" {}
locals {
  external_network_id = [for v in data.acecloud_vpcs.all.vpcs : v.id if v.router_external && v.shared][0]
}

resource "acecloud_router" "main" {
  name                        = "demo-router"
  admin_state_up              = true
  external_gateway_network_id = local.external_network_id
}

resource "acecloud_router_interface" "main" {
  router_id = acecloud_router.main.id
  subnet_id = acecloud_vpc.main.subnet_id
}

# 2. Security — allow SSH from anywhere.
resource "acecloud_security_group" "ssh" {
  name        = "demo-ssh"
  description = "Allow inbound SSH"

  rules {
    direction        = "ingress"
    protocol         = "tcp"
    port_range_min   = 22
    port_range_max   = 22
    remote_ip_prefix = "0.0.0.0/0"
    ethertype        = "IPv4"
  }
}

# 3. SSH key — omit public_key to have the platform generate one.
resource "acecloud_key_pair" "demo" {
  name = "demo-key"
}

# 4. Instance
resource "acecloud_instance" "demo" {
  name        = "demo-instance"
  description = "Demo instance with SSH access"
  flavor_id   = local.flavor_id
  boot_uuid   = local.image_id
  source_type = "image"

  delete_on_termination = true

  volumes {
    size         = 20
    boot         = true
    volume_type  = "NVMe based High IOPS Storage"
    billing_type = "hourly"
  }

  network_ids        = [acecloud_vpc.main.id]
  security_group_ids = [acecloud_security_group.ssh.id]
  key_name           = acecloud_key_pair.demo.name
  billing_type       = "monthly"
}

# 5. Public IP
resource "acecloud_floating_ip" "demo" {
  floating_network_id = local.external_network_id
}

resource "acecloud_floating_ip_association" "demo" {
  floating_ip_address = acecloud_floating_ip.demo.floating_ip_address
  instance_id         = acecloud_instance.demo.id

  depends_on = [acecloud_router_interface.main]
}

# 6. Outputs — print what you need to connect.
output "public_ip" {
  value = acecloud_floating_ip.demo.floating_ip_address
}

output "ssh_command" {
  value = "ssh -i demo-key.pem ubuntu@${acecloud_floating_ip.demo.floating_ip_address}"
}

output "private_key" {
  value     = acecloud_key_pair.demo.private_key
  sensitive = true
}

variable "acecloud_api_key_id" {
  type      = string
  sensitive = true
}
variable "acecloud_api_key_secret" {
  type      = string
  sensitive = true
}
variable "acecloud_project_id" {
  type = string
}
```

## After apply

Save the private key locally and SSH in:

```sh
terraform output -raw private_key > demo-key.pem
chmod 600 demo-key.pem
ssh -i demo-key.pem ubuntu@$(terraform output -raw public_ip)
```

